/*!
 * Data source configuration for the Power Apps SDK getClient.
 * Normally auto-generated by: pac code add-data-source -a dataverse -t contact
 *
 * This file tells the SDK which Dataverse tables are available.
 * The "tableId" maps to the Dataverse logical table name.
 * The "apis" object can be empty for Dataverse sources — the
 * runtime constructs OData URLs from the tableId automatically.
 */

export const dataSourcesInfo = {
  contacts: {
    tableId: "contact",
    apis: {} as { [key: string]: { path: string; method: string; parameters: Array<{ name: string; in: string; required: boolean; type: string }> } },
    primaryKey: "contactid",
    dataSourceType: "Dataverse",
  },
};
